---
title: "Rmarkdown Test Paper"
description: |
  Insert short description of paper (one-two sentences)
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
  - name: Jim Bob
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
journal: 
  title: "Journal of Visualization and Interaction"
volume: 0
issue: 0
doi: "insert/doi/here"
self_contained: true
repository_url: https://github.com/jo-v-i/jovi_test_paper_rmarkdown
compare_updates_url: https://github.com/jo-v-i/jovi_test_paper_rmarkdown/compare/release...master
creative_commons: CC BY-SA

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r endorsements, results="asis"}
joviRmd::print_endorsements()
```

Insert abstract here?

Distill is a publication format for scientific and technical writing, native to the web. 

Learn more about using Distill for R Markdown at <https://rstudio.github.io/distill>.

## Metadata

Check out metadata that can be set in the paper here: <https://rstudio.github.io/distill/metadata.html>.

## Test content

Here's some test content.


